import { PatternFragmentSchema, type PatternFragment } from './reference.js';

export const SEED_PATTERN_FRAGMENTS: PatternFragment[] = [
  PatternFragmentSchema.parse({
    schemaVersion: '0.1',
    fragmentId: 'pattern-organization-explanation-hierarchy',
    sourceReferenceIds: ['ext-2025-pokemon-initiative-team-structure'],
    abstractionLevel: 'structural',
    compatibleIntents: ['hierarchy'],
    semanticShape: 'hierarchy',
    relationshipShape: ['part-of'],
    readingPath: 'top-to-bottom',
    densityBand: 'balanced',
    primaryArtifactRole: 'explanation-and-hierarchy-map',
    topology: {
      family: 'organization-explanation-hierarchy',
      orderedRoles: ['title', 'operating-principle', 'hierarchy-root', 'hierarchy-descendants'],
      emphasisRule: 'Keep the operating principle distinct from the responsibility and membership hierarchy it explains.',
      groupingRule: 'Separate explanation from the hierarchy artifact; nest each authored child under its authored part-of parent.',
    },
    constraints: [
      'Preserve every authored hierarchy node and part-of relation.',
      'Do not turn responsibility or membership into a timeline or causal sequence.',
      'Do not repeat the hierarchy labels as explanatory copy.',
      'Primary Teacher structure cannot be replaced by secondary guidance.',
    ],
    prohibitedCopy: [
      'source coordinates',
      'source column ratio',
      'source palette',
      'source iconography',
      'Pokemon IP',
      'CEDEC frame',
    ],
  }),
  PatternFragmentSchema.parse({
    schemaVersion: '0.1',
    fragmentId: 'pattern-aligned-before-after-spec',
    sourceReferenceIds: ['ext-2025-shadowverse-super-evolution'],
    abstractionLevel: 'structural',
    compatibleIntents: ['comparison'],
    semanticShape: 'comparison',
    relationshipShape: ['compares-with'],
    readingPath: 'before-after',
    densityBand: 'balanced',
    primaryArtifactRole: 'aligned-feature-spec',
    topology: {
      family: 'aligned-before-after-spec',
      orderedRoles: ['title', 'message', 'column-labels', 'authored-pairs'],
      emphasisRule: 'Keep the authored intent above the comparison; emphasize the revised feature without hiding the baseline.',
      groupingRule: 'One broad field per side; align each explicitly related pair on one shared row.',
    },
    comparisonContract: {
      pairing: 'authored-compares-with', cardinality: 'one-to-one',
      beforeGroupRole: 'before', afterGroupRole: 'after',
      applicability: ['Two states of one feature with explicit same-criterion comparison edges.', 'Any positive number of authored pairs, subject to measured page capacity.'],
      boundary: ['Not a causal chain or accumulation process.', 'No inferred pairs, missing counterparts or more than two alternatives.'],
      derivedPrinciples: ['Same-criterion left/right alignment.', 'Distinguish changed rules while retaining the shared context.', 'One authored message hierarchy over the whole comparison.'],
    },
    constraints: ['Preserve every source span and comparison edge.', 'Pair by semantic relation endpoints, never text or list position.', 'Keep row alignment across both fields; do not use six repeated cards.'],
    prohibitedCopy: ['CEDEC frame', 'brand color', 'IP visual', 'source geometry', 'source wording'],
  }),
  PatternFragmentSchema.parse({
    schemaVersion: '0.1',
    fragmentId: 'pattern-accumulation-threshold-consequence',
    sourceReferenceIds: [
      'ext-2025-pokemon-problem-task-leak',
      'ext-2025-shadowverse-super-evolution',
    ],
    retrievalSupportReferenceIds: ['ref-oh-my-ppt-layout', 'ref-ppt-agent-functional'],
    abstractionLevel: 'structural',
    compatibleIntents: ['mechanism', 'state-transition'],
    semanticShape: 'causal-chain',
    relationshipShape: ['produces', 'enables', 'transitions-to', 'causes'],
    readingPath: 'guided-sequence',
    densityBand: 'balanced',
    primaryArtifactRole: 'threshold-event',
    topology: {
      family: 'accumulation-threshold-consequence',
      orderedRoles: ['accumulation', 'threshold', 'consequence'],
      emphasisRule: 'Make the threshold the strongest event without allowing it to consume the accumulation or consequence.',
      groupingRule: 'Preserve the local accumulation sequence, isolate the threshold as a boundary, and keep the consequence after that boundary.',
    },
    phaseContract: {
      semanticFamily: 'accumulation-threshold-consequence',
      requiredSemanticShape: 'causal-chain',
      regions: [
        {
          phase: 'accumulation',
          sourceGroupRoles: ['trigger', 'setup'],
          regionRole: 'support',
          flow: 'row',
          order: 1,
          weight: 2.4,
          gapToken: 'open',
          paddingToken: 'normal',
          emphasisPriority: 3,
          localSequenceRequired: true,
        },
        {
          phase: 'threshold',
          sourceGroupRoles: ['transition'],
          regionRole: 'primary-artifact',
          flow: 'overlay',
          order: 2,
          weight: 0.9,
          gapToken: 'tight',
          paddingToken: 'tight',
          emphasisPriority: 5,
          localSequenceRequired: false,
        },
        {
          phase: 'consequence',
          sourceGroupRoles: ['consequence', 'evidence'],
          regionRole: 'evidence',
          flow: 'column',
          order: 3,
          weight: 1.2,
          gapToken: 'tight',
          paddingToken: 'open',
          emphasisPriority: 4,
          localSequenceRequired: false,
        },
      ],
      regionReadingOrder: ['accumulation', 'threshold', 'consequence'],
      interPhaseRelations: [
        { from: 'accumulation', to: 'threshold', rule: 'source-relation-required' },
        { from: 'threshold', to: 'consequence', rule: 'source-relation-required' },
      ],
      applicability: {
        useWhen: [
          'Several ordered preparation or accumulation steps lead to one important state boundary and a post-boundary result.',
        ],
        requiredSignals: [
          'At least one setup group before the threshold.',
          'A transition group containing the primary artifact.',
          'At least one consequence or evidence group after the threshold.',
          'Source relations connecting accumulation to threshold and threshold to consequence.',
        ],
      },
      boundary: {
        doNotUseWhen: [
          'The content compares alternatives or before-and-after specifications.',
          'The content diagnoses a hidden omission or missing task.',
          'There is no meaningful state boundary.',
          'The groups are parallel layers rather than an ordered causal sequence.',
        ],
        forbiddenInferences: [
          'Do not invent a hidden omission or diagnosis.',
          'Do not turn the phases into a before-and-after comparison.',
          'Do not invent alternatives, labels, facts, or relations.',
        ],
      },
      provenance: {
        derivedPrinciples: [
          {
            referenceId: 'ext-2025-pokemon-problem-task-leak',
            principle: 'Reveal an important boundary inside a process as a distinct event.',
          },
          {
            referenceId: 'ext-2025-shadowverse-super-evolution',
            principle: 'Distinguish the states on each side of one boundary quickly while preserving their shared context.',
          },
        ],
        excludedMeanings: [
          'hidden omission',
          'diagnosis',
          'before-after comparison',
          'two-alternative comparison',
        ],
      },
    },
    constraints: [
      'Preserve every authored block and source relation.',
      'Preserve the local order inside accumulation.',
      'The threshold separates accumulation from consequence but does not replace either phase.',
      'Do not require an exact number of blocks inside any phase.',
    ],
    prohibitedCopy: [
      'CEDEC event frame',
      'company logo',
      'Pokemon or Shadowverse IP',
      'brand-specific color',
      'source coordinates',
      'source slide geometry',
    ],
  }),
  PatternFragmentSchema.parse({
    schemaVersion: '0.1',
    fragmentId: 'pattern-editorial-causal-spine',
    sourceReferenceIds: ['ref-oh-my-ppt-layout', 'ref-marp-reproducible'],
    abstractionLevel: 'structural',
    compatibleIntents: ['mechanism', 'timeline'],
    semanticShape: 'causal-chain',
    relationshipShape: ['produces', 'enables', 'transitions-to', 'causes'],
    readingPath: 'left-to-right',
    densityBand: 'balanced',
    primaryArtifactRole: 'mechanism-flow',
    topology: {
      family: 'editorial-causal-spine',
      orderedRoles: ['trigger', 'input', 'process', 'primary', 'modifier'],
      emphasisRule: 'Reserve the strongest interruption for the primary state transition.',
      groupingRule: 'Keep the trigger and resource acquisition quiet; join state and consequence as one conclusion.',
    },
    constraints: [
      'Preserve semantic order.',
      'Do not turn every step into an equal card.',
      'Use one dominant reading line.',
    ],
    prohibitedCopy: ['source wording', 'source artwork', 'source geometry', 'project branding'],
  }),
  PatternFragmentSchema.parse({
    schemaVersion: '0.1',
    fragmentId: 'pattern-break-threshold-field',
    sourceReferenceIds: ['ref-ppt-agent-functional', 'ref-reveal-runtime'],
    abstractionLevel: 'structural',
    compatibleIntents: ['mechanism', 'state-transition'],
    semanticShape: 'causal-chain',
    relationshipShape: ['enables', 'transitions-to', 'causes'],
    readingPath: 'center-out',
    densityBand: 'balanced',
    primaryArtifactRole: 'mechanism-flow',
    topology: {
      family: 'threshold-field',
      orderedRoles: ['trigger', 'input', 'process', 'primary', 'modifier'],
      emphasisRule: 'Treat the state transition as a threshold that reorganizes the page.',
      groupingRule: 'Place causes before the threshold and the damage modifier inside the resulting state field.',
    },
    constraints: [
      'Preserve semantic order even when the visual focus is central.',
      'The threshold must not hide the five-second condition.',
      'Avoid node-box diagrams.',
    ],
    prohibitedCopy: ['reference slide text', 'reference artwork', 'reference geometry', 'project branding'],
  }),
];
