export const PRODUCT_NAME = '기획서 디자이너'
export const PRODUCT_INTERNAL_NAME = 'deck-designer'
export const PRODUCT_APP_ID = 'com.deckdesigner.desktop'
export const PRODUCT_DATA_DIRECTORY = 'deck-designer'
export const PRODUCT_DATABASE_FILE = 'deck-designer.db'
export const PRODUCT_DEV_DATABASE_FILE = 'deck-designer.dev.db'
export const PRODUCT_LOG_DIRECTORY = 'deck-designer-logs'

export const LEGACY_DATA_DIRECTORY = 'oh-my-ppt'
export const LEGACY_DATABASE_FILE = 'ohmyppt.db'
